# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_text', models.TextField()),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(max_length=200)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='contributions',
            name='story_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozgur_modul.Storys'),
        ),
    ]
