# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozgur_modul', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributions',
            old_name='story_id',
            new_name='story',
        ),
    ]
