# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozgur_modul', '0002_auto_20170725_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributions',
            options={'verbose_name': 'Katkı', 'verbose_name_plural': 'Katkılar'},
        ),
        migrations.AlterModelOptions(
            name='storys',
            options={'verbose_name': 'Başlık', 'verbose_name_plural': 'Başlıklar'},
        ),
        migrations.AddField(
            model_name='storys',
            name='bad_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storys',
            name='contribution_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storys',
            name='good_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storys',
            name='show_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
